name: CI

on:
  push:
    branches: [ ci ]

env:
  BUILD_TYPE: MinSizeRel
  MSFS_SDK: ${{github.workspace}}
  TARGET_ARCH: AMD64
  TARGET_OS_VERSION: "10.0.19041"

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Get MSFS SDK
      uses: actions/checkout@v2
      with:
        path: SimConnect SDK
        repository: savormix/msfs-simconnect-sdk
        token: ${{ secrets.SDK_PAT }}

    - run: dir "C:\Program Files (x86)\Windows Kits\10\Include"

    - name: Configure CMake
      run: |
        & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_SYSTEM_PROCESSOR=${{ env.TARGET_ARCH }} -DCMAKE_SYSTEM_VERSION="${{ env.TARGET_OS_VERSION }}"

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: dir
      
