name: CI

on:
  push:
    branches: [ ci ]

env:
  BUILD_TYPE: MinSizeRel
  MSFS_SDK: ${{github.workspace}}

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Get MSFS SDK
      uses: actions/checkout@v2
      with:
        path: SimConnect SDK
        repository: savormix/msfs-simconnect-sdk
        token: ${{ secrets.SDK_PAT }}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: dir
      
